config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'flights#index'
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, foreign_key: 'finish_airport_id', class_name: 'Flight'
  has_many :departing_flights, foreign_key: 'start_airport_id', class_name: 'Flight'
  
  validates :code, presence: true, length: { minimum: 3, maximum: 3 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers

  validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :to_airport, foreign_key: 'finish_airport_id', class_name: 'Airport'
  belongs_to :from_airport, foreign_key: 'start_airport_id', class_name: 'Airport'
  has_many :bookings
  
  validates :date, presence: true
  validates :duration, presence: true

  default_scope -> { order(date: :asc) }

  S_HR = 3_600
  S_MIN = 60

  def from
    from_airport.code
  end

  def to
    to_airport.code
  end

  def departure_time
    date.in_time_zone(from_airport.time_zone).strftime('%B %e, %Y at %l:%M %P')
  end

  def arrival_time
    (date + duration).in_time_zone(to_airport.time_zone).strftime('%B %e, %Y at %l:%M %P')
  end

  def format_date
    date.strftime('%B %e, %Y')
  end

  def format_duration
    hours = (duration / S_HR).floor
    min = ((duration % S_HR) / S_MIN).floor
    "#{hours}hr #{min}min"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

def new
  if params[:booking][:flight_id]
    @flight = Flight.find(params[:booking][:flight_id])
    @from = Airport.find(@flight.start_airport_id)
    @to = Airport.find(@flight.finish_airport_id)
    ticket_num = params[:booking][:num_tickets].to_i
    @booking = @flight.bookings.build
    ticket_num.times { @booking.passengers.build }
  else
    flash[:danger] = "You must select a flight to continue."
    redirect_to root_url
  end
end

def create
  @flight = Flight.find(params[:booking][:flight_id])
  @booking = @flight.bookings.build(booking_params)
  if @booking&.save
    PassengerMailer.with(booking: @booking).thank_you_email.deliver_now 
    flash[:success] = 'Flight booked successfully'
    redirect_to booking_path(@booking)
  else
    render 'bookings/new'
  end
end

def show
  @booking = Booking.find(params[:id])
  @flight = @booking.flight
end


private

def booking_params
  params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name])
end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = []
    if params[:search]
      @flights = Flight.where(start_airport_id: params[:search][:from_airport_id],
                              finish_airport_id: params[:search][:to_airport_id],
                              date: DateTime.parse(params[:search][:date]))
      flash.now[:danger] = 'The flight you requested could not be found' if @flights.empty?
    end

    respond_to do |format|
      format.html
      format.xml { render :xml => @flights }
      format.json { render :json => @flights }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def flight_dates
    Flight.all.map { |f| [f.format_date, f.date] }.uniq
  end
end

app/views/bookings/new.html.erb
<%= provide(:title, 'Book a flight')%>
<%= provide(:header, render('layouts/bookings_header'))%>
<h1>Trip Itinerary</h1>
<div class='row'><%= render 'shared/itinerary', object: @flight%></div>
<hr>
<div class='row'>Passenger Info *</div></br>
    <%= form_for @booking do |f| %>
        <%= render 'shared/error_messages', object: f.object%>
        <%= f.hidden_field :flight_id, value: params[:booking][:flight_id]%>
        <%= f.fields_for :passengers do |passenger_form| %>
            <div class='row passenger-form'>
                <%= passenger_form.label :name, class: 'align-self-center' %>
                <%= passenger_form.text_field :name, placeholder: 'Passenger Name', class: 'form-control col', required: true%>
            </div>
        <% end%>
        <%= f.submit 'Confirm Booking', class: 'btn btn-primary'%>
    <% end %>
</div>

app/views/bookings/show.html.erb
<%= provide(:title, 'View Booking')%>
<%= provide(:header, render('layouts/bookings_header'))%>
<h1>Your Trip</h1>
<div class='row'><%= render 'shared/itinerary', object: @flight%></div>
<div class='row'><h2>Passengers</h2></div></br>
    <% @booking.passengers.each_with_index do |p| %>
        <div class='d-flex justify-content-start passenger-info'>
            <div><%= p.name %></div>
        </div>
    <% end %>
</div>

app/views/flights/index.html.erb
<%= provide(:title, 'Search flights')%>
<%= provide(:header, render('layouts/flights_header'))%>
<% if flash.empty? && @flights.empty? %>
    <h1>Where are you traveling?</h1>
<% end %>
<% unless @flights.empty?%>
    <%= form_for :booking, method: 'get', url: new_booking_path do |f| %>
        <%= f.hidden_field(:num_tickets, value: params[:search][:num_tickets]) %>
        <% @flights.each do |flight| %>
            <div class='booking row'>
                <%= render 'shared/itinerary', object: flight%>
                <div class='col align-self-center'>
                    <%= f.label :flight_id, 'Select Flight'%>
                    <%= f.radio_button(:flight_id, flight.id, required: true) %>
                </div>
            </div>
        <% end %>
        <%= f.submit "Book Flight", class: 'btn btn-primary'%>
    <% end %>
<% end %>

app/views/layouts/_bookings_header.html.erb
<nav class='navbar navbar-fixed-top navbar-expand-sm navbar-dark bg-dark'>
    <div class='navbar-brand'><%= link_to 'Rails Airlines', root_url, class: 'home'%></div>
</nav>

app/views/layouts/_flights_header.html.erb
<nav class='navbar navbar-fixed-top navbar-expand-sm navbar-dark bg-dark'>
    <div class='navbar-brand'><%= link_to 'Rails Airlines', root_url, class: 'home'%></div>
    <div class='container container-fluid'>
        <%= form_with scope: :search, url: flights_path,  method: :get, local: true, class: 'form-inline' do |f| %>
            <div class='form-group search-criteria'>
                <%= f.label 'From', class:'search-label'%>
                <%= f.collection_select(:from_airport_id, Airport.all, :id, :code, {}, {class: 'custom-select'}) %>
            </div>
            <div class='form-group search-criteria'>
                <%= f.label 'To', class:'search-label'%>
                <%= f.collection_select(:to_airport_id, Airport.all, :id, :code, {}, {class: 'custom-select'}) %>
            </div>
            <div class='form-group search-criteria'>
                <%= f.label 'Date', class:'search-label'%>
                <%= f.select(:date, flight_dates, {}, {class: 'custom-select'})%>
            </div>
            <div class='form-group search-criteria'>
                <%= f.label 'Passengers', class:'search-label'%>
                <%= f.select(:num_tickets, (1..9).to_a, {}, {class: 'custom-select'}) %>
            </div>
            <%= f.submit 'Search', class: 'navbar-item btn btn-outline-light'%>
        <% end %>
    </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default'%>
  </head>
  <body>
    <%= yield(:header)%>
    <div class='center jumbotron jumbotron-fluid'>
      <div class='container container-fluid'>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_itinerary.html.erb
<div class='col itinerary-info'> 
    <span><%= object.from %></span>
    <span><%= object.departure_time %></span>
</div>
<div class='col itinerary-info'>
    <span>--> </span>
    <span><%= object.format_duration%></span>
</div>
<div class='col itinerary-info'>
    <span><%= object.to %></span>
    <span><%= object.arrival_time %></span>
</div>